/**
 * @openchat/provider-kit
 *
 * 42 LLM provider unified API — one interface for OpenAI, Anthropic,
 * Ollama, OpenRouter, and 38 more.
 *
 * Quick start:
 *   import { providerRegistry, createProvider } from '@openchat/provider-kit';
 *   const provider = createProvider('openai', { apiKey: 'sk-...' });
 *   const reply = await provider.chat('gpt-4', [{ role: 'user', content: 'Hi' }]);
 */

export { ProviderError, AbortError, withRetry, withTimeout, safeProviderCall, classifyError, createCancelSignal, createRouter, createMonitor } from './providers/provider-error-adapter.js';
export { ProviderManager, providerManager, getRuntimeApiKey, getRuntimeBaseUrl, reloadRuntimeConfig, PROVIDER_ALIASES, saveProviders, updateProviderModels, addProviderEntry, DEFAULT_PROVIDER } from './providers/provider-manager.js';
export { providerRegistry, createProvider, listPresetProviders, PRESET_PROVIDERS } from './providers/provider-registry.js';
export { LocalAiProvider, createLocalProvider } from './providers/local-provider.js';
export { persistentConfig, createStore, setKeyResolver, clearKeyResolver, hasKeyResolver, resolveApiKey } from './core/persistent-config.js';
export { encodeEpcFrame, epcFromResponse, parseEpcPayload, scanNextFrame, verifyFrameCs, parseFrames,
  EPC_TYPE_LLM, EPC_TYPE_AGENT, EPC_TYPE_MEDIA, EPC_TYPE_IMAGE, EPC_TYPE_FS, EPC_TYPE_S3, EPC_TYPE_EXEC, EPC_TYPE_CHAT, EPC_TYPE_ROOM, EPC_TYPE_CALL, EPC_TYPE_SIGNAL, EPC_TYPE_SDUI, EPC_TYPE_SECURITY, EPC_TYPE_SYSTEM, EPC_TYPE_DEBUG, EPC_TYPE_FILE_XFER, EPC_TYPE_PLUGIN, EPC_TYPE_UI_INPUT, EPC_TYPE_NETWORK, EPC_TYPE_TRANSPORT, EPC_TYPE_DB, EPC_TYPE_BIZ_EXT, EPC_TYPE_EXPER, EPC_TYPE_RAW,
  EPC_SUB_CONTENT, EPC_SUB_THINKING, EPC_SUB_TOOL_CALL, EPC_SUB_TOOL_RESULT, EPC_SUB_ERROR, EPC_SUB_META,
  EPC_SUB_AGENT_STATE, EPC_SUB_TASK_START, EPC_SUB_TASK_PROGRESS, EPC_SUB_TASK_DONE, EPC_SUB_SPAWN, EPC_SUB_JOIN, EPC_SUB_MEM_READ, EPC_SUB_MEM_WRITE, EPC_SUB_SESSION_EVENT,
  EPC_SUB_LMDN, EPC_SUB_OPUS, EPC_SUB_PCM, EPC_SUB_VAD, EPC_SUB_REC_START, EPC_SUB_REC_STOP, EPC_SUB_PLAY_START, EPC_SUB_PLAY_STOP, EPC_SUB_H264, EPC_SUB_MEDIA_META,
  EPC_SUB_IMG_RAW, EPC_SUB_IMG_URL, EPC_SUB_IMG_META, EPC_SUB_IMG_GEN, EPC_SUB_IMG_ANALYZE,
  EPC_SUB_FS_LS, EPC_SUB_FS_DIR, EPC_SUB_FS_CAT, EPC_SUB_FS_READ, EPC_SUB_FS_WRITE, EPC_SUB_FS_APPEND, EPC_SUB_FS_DELETE, EPC_SUB_FS_COPY, EPC_SUB_FS_MOVE, EPC_SUB_FS_MKDIR, EPC_SUB_FS_RMDIR, EPC_SUB_FS_STAT, EPC_SUB_FS_CHMOD, EPC_SUB_FS_EXISTS, EPC_SUB_FS_TREE, EPC_SUB_FS_GLOB,
  EPC_SUB_S3_LIST_BK, EPC_SUB_S3_LIST_OBJ, EPC_SUB_S3_GET, EPC_SUB_S3_PUT, EPC_SUB_S3_DEL, EPC_SUB_S3_COPY, EPC_SUB_S3_PRESIGN, EPC_SUB_S3_UPLOAD_TK,
  EPC_SUB_EXEC_EXEC, EPC_SUB_EXEC_RESULT, EPC_SUB_EXEC_SHELL, EPC_SUB_EXEC_SHELL_OUT, EPC_SUB_EXEC_STDIN, EPC_SUB_EXEC_STDOUT, EPC_SUB_EXEC_STDERR, EPC_SUB_EXEC_EXIT, EPC_SUB_EXEC_KILL, EPC_SUB_EXEC_SIGNAL,
  EPC_SUB_CHAT_MSG, EPC_SUB_CHAT_TYPING, EPC_SUB_CHAT_REACTION, EPC_SUB_CHAT_ATTACH, EPC_SUB_CHAT_QUOTE, EPC_SUB_CHAT_DELETE, EPC_SUB_CHAT_EDIT, EPC_SUB_CHAT_RECEIPT, EPC_SUB_CHAT_HISTORY,
  EPC_SUB_ROOM_CREATE, EPC_SUB_ROOM_JOIN, EPC_SUB_ROOM_LEAVE, EPC_SUB_ROOM_MEMBERS, EPC_SUB_ROOM_MEMBER_IN, EPC_SUB_ROOM_MEMBER_OUT, EPC_SUB_ROOM_MEMBER_MUTE, EPC_SUB_ROOM_SETTINGS, EPC_SUB_ROOM_INVITE,
  EPC_SUB_CALL_IN, EPC_SUB_CALL_OUT, EPC_SUB_CALL_ACCEPT, EPC_SUB_CALL_REJECT, EPC_SUB_CALL_END, EPC_SUB_CALL_MUTE, EPC_SUB_CALL_UNMUTE, EPC_SUB_CALL_SPEAKER, EPC_SUB_CALL_VOLUME,
  EPC_SUB_SIG_OFFER, EPC_SUB_SIG_ANSWER, EPC_SUB_SIG_ICE, EPC_SUB_SIG_PING, EPC_SUB_SIG_PONG, EPC_SUB_SIG_PRESENCE, EPC_SUB_SIG_PEERS,
  EPC_SUB_SDUI_TREE, EPC_SUB_SDUI_DIFF, EPC_SUB_SDUI_NAV, EPC_SUB_SDUI_MODAL, EPC_SUB_SDUI_TOAST, EPC_SUB_SDUI_SNACK, EPC_SUB_SDUI_DIALOG, EPC_SUB_SDUI_REFRESH, EPC_SUB_SDUI_THEME, EPC_SUB_SDUI_LAYOUT, EPC_SUB_SDUI_INPUT, EPC_SUB_SDUI_STATE,
  EPC_SUB_SEC_PUBKEY, EPC_SUB_SEC_ENVELOPE, EPC_SUB_SEC_SIGN, EPC_SUB_SEC_AUTH, EPC_SUB_SEC_CHALLENGE, EPC_SUB_SEC_SESSION, EPC_SUB_SEC_PERM,
  EPC_SUB_SYS_LOG, EPC_SUB_SYS_METRIC, EPC_SUB_SYS_CONFIG, EPC_SUB_SYS_ALERT, EPC_SUB_SYS_HEALTH, EPC_SUB_SYS_VERSION, EPC_SUB_SYS_STATUS, EPC_SUB_SYS_ERR_LOG, EPC_SUB_SYS_WARN, EPC_SUB_SYS_INFO, EPC_SUB_SYS_DEBUG,
  EPC_SUB_DBG_TRACE, EPC_SUB_DBG_INSPECT, EPC_SUB_DBG_PROFILE, EPC_SUB_DBG_BREAK, EPC_SUB_DBG_WATCH, EPC_SUB_DBG_STACK, EPC_SUB_DBG_HEAP, EPC_SUB_DBG_MEM_DUMP,
  EPC_SUB_FILE_BLOB, EPC_SUB_FILE_META, EPC_SUB_FILE_CHUNK, EPC_SUB_FILE_XFER_START, EPC_SUB_FILE_XFER_DONE, EPC_SUB_FILE_XFER_CANCEL,
  EPC_SUB_PLUGIN_LOAD, EPC_SUB_PLUGIN_UNLOAD, EPC_SUB_PLUGIN_EVENT, EPC_SUB_PLUGIN_REG_TOOL, EPC_SUB_PLUGIN_EXEC_TOOL, EPC_SUB_PLUGIN_RESULT,
  EPC_SUB_UI_KEY_DOWN, EPC_SUB_UI_KEY_UP, EPC_SUB_UI_MOUSE_MOVE, EPC_SUB_UI_MOUSE_DOWN, EPC_SUB_UI_MOUSE_UP, EPC_SUB_UI_SCROLL, EPC_SUB_UI_TOUCH, EPC_SUB_UI_GESTURE, EPC_SUB_UI_CLIPBOARD, EPC_SUB_UI_DRAG, EPC_SUB_UI_DROP,
  EPC_SUB_NET_DISC, EPC_SUB_NET_ROUTE, EPC_SUB_NET_SYNC, EPC_SUB_NET_GOSSIP, EPC_SUB_NET_PEER, EPC_SUB_NET_TOPOLOGY,
  EPC_SUB_TP_STREAM, EPC_SUB_TP_ACK, EPC_SUB_TP_HEARTBEAT, EPC_SUB_TP_FLOW_CTL, EPC_SUB_TP_RETRY, EPC_SUB_TP_BACKPRESS, EPC_SUB_TP_CONNECT, EPC_SUB_TP_DISCONNECT, EPC_SUB_TP_RECONNECT,
  EPC_SUB_DB_QUERY, EPC_SUB_DB_EXEC, EPC_SUB_DB_INSERT, EPC_SUB_DB_UPDATE, EPC_SUB_DB_DELETE, EPC_SUB_DB_SCHEMA, EPC_SUB_DB_MIGRATE, EPC_SUB_DB_INDEX, EPC_SUB_DB_TX_BEGIN, EPC_SUB_DB_TX_COMMIT, EPC_SUB_DB_TX_ROLLBACK
} from './providers/epc-codec.js';
